### ISSUE TITLE
ARC Handling Bug in 0.12.0 when Extracting Links

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/aut#154]
This bug is confirmed for me on aut 0.12.0, but when I rolled back to 0.10.0, the script worked.

Running following script on Ubuntu 16 AWS machine.

```
import io.archivesunleashed.spark.matchbox.{ExtractDomain, ExtractLinks, RecordLoader}
import io.archivesunleashed.spark.rdd.RecordRDD._
val links = RecordLoader.loadArchives("/data/cpp/*.arc.gz", sc).map(r => (r.getCrawlDate, ExtractLinks(r.getUrl, r.getContentString))).flatMap(r => r._2.map(f => (r._1, ExtractDomain(f._1).replaceAll("^\\s*www\\.", ""), ExtractDomain(f._2).replaceAll("^\\s*www\\.", "")))).filter(r => r._2 != "" && r._3 != "").countItems().filter(r => r._2 > 5).saveAsTextFile("/data/all-links")
```
On aut 0.10.0 it works. 

On aut 0.12.0, I get the following error. [Full Gist here](https://gist.github.com/ianmilligan1/babd67e78638495bba9f9fc36eb30b5f).

```
[Stage 0:>                                                      (19 + 8) / 2441]2017-12-15 16:32:17,654 [Executor task launch worker for task 26] ERROR Executor - Exception in task 26.0 in stage 0.0 (TID 26)
java.lang.StackOverflowError
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:279)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:142)
	at org.jsoup.parser.HtmlTreeBuilderState$15.anythingElse(HtmlTreeBuilderState.java:1207)
	at org.jsoup.parser.HtmlTreeBuilderState$15.process(HtmlTreeBuilderState.java:1201)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:137)
	at org.jsoup.parser.TreeBuilder.processStartTag(TreeBuilder.java:66)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:707)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:142)
	at org.jsoup.parser.HtmlTreeBuilderState$15.anythingElse(HtmlTreeBuilderState.java:1207)
	at org.jsoup.parser.HtmlTreeBuilderState$15.process(HtmlTreeBuilderState.java:1189)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:137)
	at org.jsoup.parser.HtmlTreeBuilderState$7.process(HtmlTreeBuilderState.java:708)
	at org.jsoup.parser.HtmlTreeBuilder.process(HtmlTreeBuilder.java:142)
at org.jsoup.parser.HtmlTreeBuilderState$15.anythingElse(HtmlTreeBuilderState.java:1207)
```

**Comment by ianmilligan1** [comment]
I'm going to try recompiling 0.12.0 with just swapping out the new `ArcRecordUtils` with the old one, see how it shakes out.

**Comment by ianmilligan1** [comment]
Currently going back through the tree to see where this error creeps in.

**Comment by ianmilligan1** [comment]
OK the error makes its first appearance with this commit: https://github.com/archivesunleashed/aut/commit/053c7de694810202d7b9dc5d54461691c9eff7bf, which is all changes to the `pom.xml`.

Maybe something to do with the jsoup parser?
