### ISSUE TITLE
RecordLoader.loadArchives fails with nested dirs

### ISSUE THREAD

**Issue by dportabella** [archivesunleashed/aut#169]
**Update: the issue was not about symbolic links, but with nested dirs. I've updated the question**

I have a warc file at `/data/test/sample.warc.gz` and the following code works as expected:

```
$ spark-shell --verbose --packages "io.archivesunleashed:aut:0.12.0"
import io.archivesunleashed.spark.archive.io.ArchiveRecord
import io.archivesunleashed.spark.matchbox.RecordLoader
val file = "/data/test"
RecordLoader.loadArchives(file, sc).foreach(archiveRecord => println(archiveRecord.getUrl))
```

However, if I create the following dir structure with nested dirs, and run it again:
```
$ mkdir -p /data/test1/test2
$ cp /data/test/sample.warc.gz /data/test1/test2
$ find /data/test1
/data/test1
/data/test1/test2
/data/test1/test2/sample.warc.gz

$ spark-shell --verbose --packages "io.archivesunleashed:aut:0.12.0"
import io.archivesunleashed.spark.archive.io.ArchiveRecord
import io.archivesunleashed.spark.matchbox.RecordLoader
val file = "/data/test1"
RecordLoader.loadArchives(file, sc).foreach(archiveRecord => println(archiveRecord.getUrl))
```

it fails with:
```
java.lang.NullPointerException
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:419)
  at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:125)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2094)
  at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:918)
  at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:916)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.foreach(RDD.scala:916)
  ... 48 elided
```

**Comment by dportabella** [comment]
I just see that replacing `val file = "/data/test1"` by `val file = "/data/test1/*"` solves the issue.

The issue is also soved setting recursive to true:
```
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat
sc.hadoopConfiguration.set(FileInputFormat.INPUT_DIR_RECURSIVE,"true")
```
However, I guess that throwing a NullPointerException is a bug? And if so, is it a bug of Spark or of a bug of `aut`?

**Comment by ianmilligan1** [comment]
This is all spark related rather than aut related (it's tripping up stuff in the spark libraries). I think it's pretty easy to generate NullPointerExceptions using Spark. Or at least I am good at it. 😄 

Given that this isn't really an AUT error I'm going to close the issue but thanks for logging this. I'm sure it is something we will run into down the road.
